export const GET_ERRORS = 'GET_ERRORS';

// Auth types
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_PREFERENCES = 'SET_USER_PREFERENCES';

// Weather types
export const WEATHER_LOGS_LOADING = 'WEATHER_LOGS_LOADING';
export const GET_PRIVATE_WEATHER_LOGS = 'GET_PRIVATE_WEATHER_LOGS';
export const GET_PUBLIC_WEATHER_LOGS = 'GET_PUBLIC_WEATHER_LOGS';
export const GET_FAVORITE_WEATHER_LOGS = 'GET_FAVORITE_WEATHER_LOGS';
export const GET_DEVICE_WEATHER_LOGS = 'GET_DEVICE_WEATHER_LOGS';

// Device types
export const DEVICES_LOADING = 'DEVICES_LOADING';
export const GET_PUBLIC_DEVICES = 'GET_PUBLIC_DEVICES';
export const GET_PRIVATE_DEVICES = 'GET_PRIVATE_DEVICES';
export const GET_DEVICE = 'GET_DEVICE';

// Admin types
export const USERS_LOADING = 'USERS_LOADING';
export const GET_ALL_USERS = 'GET_ALL_USERS';
