---
- name: install test
  hosts: all
  become: true
  
  tasks:
  
          #  - name: push package list
          #shell: scp dietpi@192.168.50.236:pkg.list pkg.list


  - name: upgrade system
    apt: 
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 
  
  - name: install default packages from list 
    shell: apt install $(pkg.list)
    

