---

- name: back up stations
  hosts: all
  become: true


  tasks: 
  - synchronize:
      mode: pull
      src: /home/ansible
      dest: /home/dietpi/backups/{{ansible_hostname}}
      archive: yes
