---
- name: Push Data
  hosts: stations
  become: yes
  become_method: sudo

  tasks:
  - cron:
      name: Push Data
      user: root
      minute: "*/15"
      job: "python /home/dev/skypi/pi/py/sensor_info.py"
