---
- name: script push
  hosts: all
  vars:
    py:  /home/dietpi/skypi/pi/py
    lib: /home/dietpi/skypi/pi/ansible/library
    php: /home/dietpi/skypi/pi/ansible/php
  gather_facts: false
  become: true

  tasks:
  - name: push script dirs
    copy: 
      src: "{{ item }}"
      dest: /home/dietpi/
      owner: dietpi
      group: dietpi
      mode: 0644
    with_items: 
        - "{{ py }}"
        - "{{ lib }}"
        - "{{ php }}"
     
