---
- name: script push
  hosts: all
  vars_files:
    - ../group_vars/all
  


  tasks:
  - name: update local directories
    shell: cd ~/skypi && git pull 
    when: inventory_hostname in groups['control']

  - name: push script dirs
    copy: 
      src: "{{ item }}"
      dest: /home/ansible/
      owner: ansible
      mode: 0644
    when: inventory_hostname in groups['stations']
    with_items: 
        - "{{ py }}"
        - "{{ lib }}"
        
     
