---
- name: script push
  hosts: all
  gather_facts: false
  become: true

  tasks:

  - name: push py folder
    copy: 
      src: /home/dietpi/skypi/pi/py
      dest: /home/dietpi/skypi/pi/
      owner: dietpi
      group: dietpi
      mode: 0644
  - name: push library
    copy:
      src: /home/dietpi/skypi/pi/ansible/library
      dest: /home/dietpi/
      owner: dietpi
      group: dietpi
      mode: 0644
  - name: push php
    copy:
      src: /home/dietpi/skypi/pi/ansible/php
      dest: /home/dietpi
      owner: dietpi
      group: dietpi
      mode: 0644
