---
- name: initial set up
  hosts: all
  become: yes

  tasks:
  - name: push package list
    copy:
      src: /home/dietpi/skypi/pi/ansible/library/pkg.list
      dest: /home/dietpi/pkg.list
      owner: ansible
      group: sudo
      mode: 0644

      #- name: install aptitude
      #shell: sudo apt-get install aptitude
      

  - name: upgrade system
    apt:
     upgrade: yes
     update_cache: yes
     cache_valid_time: 86400 
   

  - name: install default packages from list 
    shell: apt install $(< pkg.list)
   
    

