---
- name: install pip packages
  hosts: all
  become: yes
  
  tasks:
  - name: install wheel
    shell: pip install wheel

  - name: install setuptools 
    shell: pip install setup tools      

  - name: install default pip packages from list 
    shell: pip install -r  ~/pip.list
     
    

