- name: Add the ansible user 
  hosts: all
  become: true 
  tasks:
  
  

  - name: add ansible user
    user:
      name: ansible
      group: sudo
  - name: add ssh key
    authorized_key:
      user: ansible
      state: present
  - name: push sudoers config
    copy:
      src: /home/dietpi/sudoers
      dest: /etc/sudoers
      owner: root 
