- name: Add the ansible user 
  hosts: all
  become: true 
  tasks:
  
  

  - name: add
    user:
      name: ans
      group: sudo
  - name: push sudoers config
    copy:
      src: /home/dietpi/sudoers
      dest: /etc/sudoers
      owner: root 
