---

- name: configure WiFi
  hosts: jacob
  become: true
  become_method: sudo


  tasks:

  - name: push wpa_supplicant config
    copy: 
      src: ~/wpa.conf
      dest: /etc/wpa_supplicant/wpa_supplicant.conf
      owner: root
  - name: reboot
    shell: reboot

